### ISSUE TITLE
Reddit Video bot

### ISSUE THREAD

**Issue by Yokok2** [JasonLovesDoggo/JasonLovesDoggo#10]
Hey man I'm trying to install the reddit video bot step by step and i keep running to one issue when i paste "pip install -r requirements.txt" to cmd i get the information ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' . And i have it in the folder which was in the ZIP file

**Comment by JasonLovesDoggo** [comment]
Ask in the main repo
