### ISSUE TITLE
Bug on RedditBot

### ISSUE THREAD

**Issue by X023301** [JasonLovesDoggo/JasonLovesDoggo#8]
Hey,

I hope I don't disturb you in any way. You closed my https://github.com/elebumm/RedditVideoMakerBot/issues/1222, and I wanted to ask where the duplicate is. Because the first error message is Traceback, but after that it comes the error "invalid continuation byte". 
 I could not find any bugs related to it.

**Comment by X023301** [comment]
I got my problem but it was not a duplicate.

**Comment by JasonLovesDoggo** [comment]
Search again there was at least one other with the exact error
